### ISSUE TITLE
无法识别从任意位置打开的.lake文件

### ISSUE THREAD

**Issue by Huirey** [ilimei/vscode-plugin-lake-editor#10]
从桌面新建.lake文件，并设置为使用VScode打开
![image](https://github.com/user-attachments/assets/147c8648-f4a8-4f12-af97-c83233424672)
无法调用语雀面板
![image](https://github.com/user-attachments/assets/f89f45df-2f91-49b7-9416-57edd0cdb102)

**Comment by ilimei** [comment]
可以试试用vscode打开图片文件，vscode启动文件编辑默认是从文本编辑
