### ISSUE TITLE
关于语雀导出的lake

### ISSUE THREAD

**Issue by tinaxinoo** [ilimei/vscode-plugin-lake-editor#5]
语雀导出的lake内可能存在插件不支持的控件,如链接卡片
![image](https://github.com/ilimei/vscode-plugin-lake-editor/assets/109138472/dc8cd25b-c405-4051-9e88-31637d491796)
导致无法浏览lake内的所有内容.能否屏蔽掉这些不支持的内容,让其他内容正常显示

**Comment by ilimei** [comment]
v0.0.12
