### ISSUE TITLE
VSCode切换亮暗主题导致显示问题

### ISSUE THREAD

**Issue by Zoltan-code** [ilimei/vscode-plugin-lake-editor#7]
在明亮主题下打开.lake文件后，输入内容后，切换成暗黑主题，显示效果如下：
![image](https://github.com/ilimei/vscode-plugin-lake-editor/assets/24618122/4293cb71-75d5-4cef-9e2d-387db4498968)

在暗黑主题下打开.lake文件后，输入内容后，切换成明亮主题，显示效果如下：
![image](https://github.com/ilimei/vscode-plugin-lake-editor/assets/24618122/d9cc3f9e-d098-4ef3-8ef8-da7df7251fcc)

**Comment by ilimei** [comment]
v0.0.12
