### ISSUE TITLE
光标失焦问题

### ISSUE THREAD

**Issue by xiuzhi-pomelo** [ilimei/vscode-plugin-lake-editor#8]
![image](https://github.com/ilimei/vscode-plugin-lake-editor/assets/51158769/2d72847b-c7c0-408e-af20-f819fcba7f30)
鼠标聚焦在输入位置，切换到浏览器，点击浏览器页面，再切换回vscode，鼠标就失去焦点，不聚焦在原来的位置了。

在vscode内新建其他问题，切换后返回，鼠标还是聚焦在原位置

**Comment by ilimei** [comment]
v0.0.12
